server:
  port: ${SERVER_PORT:8093}

management:
  security:
    enabled: ${MANAGEMENT_SECURITY_ENABLED:true}
    allowedOrigin: ${ALLOWED_FRONTEND_ORIGIN:*}
    allowedHeaders: ${ALLOWED_HEADERS:*}

jwt:
  secret: "${SNL_FRONTEND_JWT_SECRET:AlaMaKotaAKotMaAle}"

liquibase:
  enabled: ${ENABLE_DB_MIGRATE_IN_SERVICE:true}
  change-log: classpath:db/db-changelog.yaml

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:dummy}

#If you use a database then uncomment below lines and update db properties accordingly leaving tomcat connection settings unchanged.
spring:
  application:
    name: snl-notes
  datasource:
      url: jdbc:postgresql://${SNL_NOTES_DB_HOST:localhost}:${SNL_NOTES_DB_PORT:5433}/${SNL_NOTES_DB_NAME:snl}${SNL_NOTES_DB_PARAMS:?}
      username: ${SNL_NOTES_DB_USERNAME:snluser}
      password: ${SNL_NOTES_DB_PASSWORD:snlpass}
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
#      properties:
#        charSet: UTF-8
#      tomcat:
#        max-active: 10
#        max-idle: 10
#        min-idle: 2
#        max-wait: 10000
#        test-on-borrow: true
#        test-on-connect: true
#        test-on-idle: true
#        validation-query: "SELECT 1"
#        time-between-eviction-runs-millis: 10000
#        test-while-idle: true
#        test-on-return: true
#        remove-abandoned: true
#        remove-abandoned-timeout: 60
#        log-abandoned: true
#        abandon-when-percentage-full: 0
